config/routes.rb
Rails.application.routes.draw do
  root to: 'novo#index'
  get 'show', to: 'novo#show'
  get 'busca', to: 'novo#index'
  #post "/api/v1/clientes", to: 'api#create'
  resources :dogs
end

app/models/api.rb
class Api < ApplicationRecord
  def teste
    "um texto qualquer"
  end

  def validar_cpf(cpf)
    return false if cpf.nil?
    nulos = %w{12345678909 11111111111 22222222222 33333333333 44444444444 55555555555 66666666666 77777777777 88888888888 99999999999 00000000000 12345678909}
    valor = cpf.scan /[0-9]/
    if valor.length == 11
      unless nulos.member?(valor.join)
        valor = valor.collect{|x| x.to_i}
        soma = 10*valor[0]+9*valor[1]+8*valor[2]+7*valor[3]+6*valor[4]+5*valor[5]+4*valor[6]+3*valor[7]+2*valor[8]
        soma = soma - (11 * (soma/11))
        resultado1 = (soma == 0 or soma == 1) ? 0 : 11 - soma
        if resultado1 == valor[9]
          soma = valor[0]*11+valor[1]*10+valor[2]*9+valor[3]*8+valor[4]*7+valor[5]*6+valor[6]*5+valor[7]*4+valor[8]*3+valor[9]*2
          soma = soma - (11 * (soma/11))
          resultado2 = (soma == 0 or soma == 1) ? 0 : 11 - soma
          return true if resultado2 == valor[10] # CPF válido
        end
      end
    end
    return false # CPF inválido
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/dog.rb
class Dog < ApplicationRecord
  include PgSearch::Model
  pg_search_scope :busca,
    against: [ :description, :temper ],
    using: {
      tsearch: { prefix: true } # <-- now `superman batm` will return something!
    }
end

app/controllers/api_controller.rb
class ApiController < ApplicationController
  include HTTParty
  base_uri 'api.thedogapi.com'

  def initialize
    @dado_captado = {}
  end

  def captado
    self.class.get('/v1/breeds', @dado_captado)
  end

  def detalhado(id)
    self.class.get("/v1/breeds/#{id}", @dado_captado)
  end

  def foto
    self.class.get("/v1/images/search", @dado_captado)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/dogs_controller.rb
class DogsController < ApplicationController
  require "json"
  require "open-uri"

  def index
    if params[:query].present?
      @dogs = Dog.busca(params[:query])
    else
      @dogs = Dog.all
    end
  end

  def show
    @dog = Dog.find(params[:id])
  end

  def new
    @dog = Dog.new
  end

  def create
    @dog = Dog.new(dog_params)
    @dog.save
    redirect_to dog_path(@dog)
  end

  def popular
    @dogs = Dog.where(popularity: 5)
  end

  private

  def dog_params
    params.require(:dog).permit(:description, :temper, :origin, :popularity)
  end
end

app/controllers/novo_controller.rb
class NovoController < ApplicationController
  before_action :set_dados_captados

  def index
    if params[:query].present?
      @racas = @dados.captado.find { |x| x["name"] == params[:query] }
    else
      @foto = @dados.foto[0]["url"]
      @racas = @dados.captado
      @paginado = Kaminari.paginate_array(@racas).page(params[:page]).per(10)
    end
  end

  def show
    @raca = @dados.detalhado(params[:id])
  end

  def set_dados_captados
    @dados = ApiController.new
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/dogs/index.html.erb
<div class="contain">
  <h1>Here's your dog list bro</h1>
</div>

<div class="contain">
  <%= form_tag dogs_path, method: :get do %>
    <%= text_field_tag :query,
      params[:query],
      class: "form-control",
      placeholder: "Find a dog breed"
    %>
    <%= submit_tag "Search", class: "btn btn-primary" %>
  <% end %>
</div>

<div class="contain">
  <% @dogs.each do |dog| %>
    <%= link_to dog.description, dog_path(dog) %>
  <% end %>
</div>

<div class="contain">
  <%= link_to 'Criar nova raça', new_dog_path, class: "btn btn-ghost" %>
</div>

app/views/dogs/new.html.erb
<%= form_for(@dog) do |f| %>
  <%= f.label :description %>
  <%= f.text_field :description %>
  <%= f.label :temper %>
  <%= f.text_field :temper %>
  <%= f.label :origin %>
  <%= f.text_field :origin %>
  <%= f.label :popularity %>
  <%= f.text_field :popularity %>
  <%= f.submit %>
<% end %>

app/views/dogs/popular.html.erb
<div class="contain">
  <h1>The most popular breed is this guy</h1>
</div>

<div class="card-trip">
  <%= image_tag "golden.png", alt: "Le Wagon", width: 100 %>
  <div class="card-trip-infos">
    <div>
      <h2>
       <% @dogs.each do |dog| %>
        <%= dog.description %>
       <% end %></h2>
    </div>
    <h2 class="card-trip-pricing">Queridinho</h2>
    <img src="https://images.unsplash.com/photo-1518717758536-85ae29035b6d?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1740&q=80" class="card-trip-user avatar-bordered" />
  </div>
</div>

<div class="contain">
  <%= link_to 'Ver raças', dogs_path, class: "btn btn-ghost"  %>
</div>

app/views/dogs/show.html.erb
<h1>Esse dog é <%= @dog.description %> </h1>
<p> O temperamento é <%= @dog.temper %> <p>
<p> A origem é <%= @dog.origin %> <p>
<p> A popularidade é <%= @dog.popularity %> <p>

<%= link_to "Lista", dogs_path %>

app/views/dogs/teste.html.erb
<%= @a %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Dogs</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/novo/index.html.erb
<div class="banner" style="background-image: url(<%=@foto%>);">
  <div class="disclaimer">

  <%= link_to root_path do %>
   <%= image_tag "dog.jpg", class: "img" %>
  <% end %>

  </div>
  <div class="container">
    <%= form_tag root_path, method: :get do %>
      <%= text_field_tag :query,
        params[:query],
        class: "form-control",
        placeholder: "Find a breed"
      %>
    <%= submit_tag "Search", class: "btn btn-primary" %>
    <% end %>
  </div>

  <div class="card">
    <table>
      <thead class="title">
        <td>Breed</td>
        <td>Life Span</td>
        <td>Temperament</td>
        <td>Group</td>
      </thead>

      <tbody class="breed">
          <%  if params[:query].present? %>
            <tr>
              <td><h1><%= @racas["name"] %></h1></td>
              <td><%= @racas["life_span"] %></td>
              <td><%= @racas["temperament"] %></td>
              <td><%= @racas["breed_group"] %></td>
            </tr>
          <% else %>
            <%= paginate @paginado, left: 1, right: 3 %>
            <%  @paginado.each do |name| %>
              <tr>
                <td><%= link_to name["name"], show_path(id: name["id"])%></td>
                <td><%= name["life_span"] %></td>
                <td><%= name["temperament"] %></td>
                <td><%= name["breed_group"] %></td>
              </tr>
            <% end %>
          <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/novo/show.html.erb
<div class="disclaimer">
  <%= @raca["name"] %>
  <%= @raca["weight"]["imperial"] %>
  <%= @raca["height"]["imperial"] %>
  <%= @raca["origin"] %>
  <%= @raca["temperament"] %>
</div>